name: Dependency Check
description: Runs OWASP dependencycheck against the repo to generate a report on vulnerabilities"
inputs:
    Project-Name:
        required: false
        default: '$GITHUB_REPOSITORY'
    Source-Location:
        required: false
        default: '/github/workspace'
    Report-Format:
        required: false
        default: 'ALL'
    Report-Location:
        required: false
        default: '/github/workspace/reports'
    Log-Name:
        required: false
        default: log.txt
runs:
    using: 'docker'
    image: docker://public.ecr.aws/govtechsg/cicd-images:dependency-check-latest
    args:
        - '--scan'
        - '${{ inputs.Source-Location }}'
        - '--format'
        - '${{ inputs.Report-Format }}'
        - '--project'
        - '${{ inputs.Project-Name }}'
        - '--out'
        - '${{ inputs.Report-Location }}'
        - '--log'
        - '${{ inputs.Report-Location }}/${{ inputs.Log-Name }}'